[project]
name = "atri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiosqlite>=0.21.0",
    "faiss-cpu>=1.10.0",
    "networkx>=3.4.2",
    "nomic[local]",
    "scipy>=1.15.3",
    "numpy>=2.2.4",
]
